### ISSUE TITLE
Wrong download link

### ISSUE THREAD

**Issue by Fishermanykx** [Spider-scnu/TSP#3]
Hi, @Spider-scnu , thank you for make your code and dataset opensource. However, the link of TSP-200-500-1000-testset-downloading-link in the README.md directs me to the zipfile of heatmap instead of files like tsp_200_concorde.txt. I wonder if you put the wrong link, looking forward to your reply :)

**Comment by Spider-scnu** [comment]
The link of TSP-200-500-1000 testset has been updated.
